# Configuration Apache pour servir Dolibarr sous /crm
ServerName broska.hd.free.fr

Alias /crm /var/www/html

<Directory /var/www/html>
    Options +FollowSymLinks
    AllowOverride All
    Require all granted
    
    <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /crm/
    </IfModule>
</Directory>
